### ISSUE TITLE
About ideas on receptive field

### ISSUE THREAD

**Issue by CaelynCheung1996** [josedolz/SemiDenseNet#1]
Hi Jose,

Recently I am running your method on MR segmentation task. I selected a small rectangle region as ROI to segment the target into it. The DICE is not bad but it seems like there's always some fragments (some tiny spots I consider) wrongly segmented, which is obviously not belonged to my target. Is that cause by the small receptive field problem or do you have any idea what is this about? Thanks.

**Comment by josedolz** [comment]
Hi @CaelynCheung1996 

This isolated outliers might be due to the limited receptive field, as you said. If they are not connected to your main target you could remove them with some easy post-processing. A solution for that would be to replace the convolutions by dilated convolutions, so that you increase the receptive field of the net without degrading the performance.

Jose.

**Comment by CaelynCheung1996** [comment]
Thanks for your opinion Jose. I think I will try CRF first to see it it works. BTW, when will the latest HyperDenseNet be released?

**Comment by josedolz** [comment]
I expect to release the code of HyperDenseNet in the following weeks (max 4-5 weeks).

Best,
